version: '2'

services:

  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: 'developmentseed/geolambda-base:latest'
    entrypoint: /bin/bash

  core:
    build:
      context: .
    image: 'developmentseed/geolambda:latest'
    entrypoint: /bin/bash
    links:
      - base

#  runner:
#    build:
#      context: .
#      dockerfile: Dockerfile.runner
#    image: 'developmentseed/geolamnda:runner'
#    links:
#      - base
