version: 2

jobs:
  build:
    working_directory: /project
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.12.0 awscli==1.11.76
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/project.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/project.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker-compose build #--cache-from=project
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/project.tar project
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/project.tar
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              read -r ver<CHANGES.md
              VERSION=${ver::-1}
              echo VERSION: $VERSION
              #docker tag :${CIRCLE_SHA1}"
              #docker push "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"
            fi
