version: 2

jobs:
  build_and_deploy:
    working_directory: /project
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.12.0 awscli==1.11.76
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/project.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/project.tar | true
      - run:
          name: Build application Docker image
          command: |
            VERSION=$(cat VERSION)
            docker build . -t developmentseed/geolambda:${VERSION} #--cache-from=project
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/project.tar developmentseed/geolambda
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/project.tar
      - deploy:
          name: Push application Docker image
          command: |
            VERSION=$(cat VERSION)
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git tag ${VERSION}
            git push origin ${VERSION}
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag developmentseed/geolambda:latest developmentseed/geolambda:${VERSION}
            docker push developmentseed/geolambda:latest
            docker push developmentseed/geolambda:${VERSION}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only: master
